"""Add alert and notification column

Revision ID: c858668fee6f
Revises: ec4fe161b838
Create Date: 2024-12-08 20:39:59.226311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c858668fee6f'
down_revision = 'ec4fe161b838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_notified_time', sa.DateTime(), nullable=True))
        batch_op.drop_column('time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('last_notified_time')

    # ### end Alembic commands ###
